#!/usr/bin/python3

import sys
import subprocess

print("installing dependencies...")
subprocess.check_call([sys.executable, "-m", "pip", "install", "-r", "requirements.txt"])

if len(sys.argv) - 1 != 2:
    print(f"Usage: {sys.argv[0]} [program] [input]")
    exit(0)

sys.argv = [sys.argv[0], sys.argv[1], "-i", sys.argv[2], "-d", "bad.txt", "-v"]

from securitears import __main__