#!/usr/bin/python3
import sys

if len(sys.argv) - 1 != 2:
    print(f"Usage: {sys.argv[0]} [program] [input]")
    exit(0)

sys.argv = [sys.argv[0], sys.argv[1], "-i", sys.argv[2], "-d", "bad.txt", "-v"]

from securitears import __main__